# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 05:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Q', 'QUEUED'), ('P', 'PROCESSING'), ('F', 'FINISHED'), ('E', 'EXPIRED')], default='Q', max_length=1)),
                ('archive_file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('expiry', models.DateTimeField(default=datetime.datetime(2017, 7, 28, 5, 44, 26, 600608))),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('PE', 'PERSONAL')], default='PU', max_length=2)),
                ('subject', models.CharField(max_length=255)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='message_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ip_address', models.CharField(blank=True, max_length=16)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField()),
                ('threads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='messenger.MessageThread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_copies', to='messenger.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('domain', models.CharField(max_length=512)),
                ('site_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=32)),
                ('access_secret', models.CharField(max_length=256)),
                ('access_key', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='threads',
            field=models.ManyToManyField(related_name='profiles', through='messenger.ProfileThread', to='messenger.MessageThread'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.SiteProfile'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='messenger.MessageThread'),
        ),
        migrations.AddField(
            model_name='archive',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_requests', to='messenger.Profile'),
        ),
        migrations.AddField(
            model_name='archive',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='messenger.MessageThread'),
        ),
    ]
