# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 8, 45, 32, 401826)),
        ),
    ]
