# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def create_profiles(apps, schema):
        Profile = apps.get_model('messenger', 'Profile')
        User = apps.get_model('auth', 'User')

        for user in User.objects.filter(profile=None):
            Profile.objects.create(owner=user)


    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_profiles),
    ]
