# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20170710_0653'),
        ('messenger', '0003_auto_20170710_0857'),
    ]

    operations = [
    ]
