# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_merge_20170712_0408'),
        ('messenger', '0004_merge_20170712_0407'),
    ]

    operations = [
    ]
