# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_merge_20170712_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='message_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
