# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20170714_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilethread',
            old_name='thread',
            new_name='threads',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thread',
        ),
        migrations.AddField(
            model_name='profile',
            name='threads',
            field=models.ManyToManyField(related_name='profiles', through='messenger.ProfileThread', to='messenger.MessageThread'),
        ),
    ]
