# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_auto_20170714_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Q', 'QUEUED'), ('P', 'PROCESSING'), ('F', 'FINISH PROCESSING'), ('D', 'DONE')], default='Q', max_length=1)),
                ('archive_file', models.FileField(upload_to='')),
            ],
        ),
    ]
