# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_requests', to='messenger.Profile'),
        ),
    ]
