# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_archive'),
        ('messenger', '0004_auto_20170713_0234'),
    ]

    operations = [
    ]
