# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_archive_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('Q', 'QUEUED'), ('P', 'PROCESSING'), ('F', 'FINISH PROCESSING'), ('E', 'EXPIRED')], default='Q', max_length=1),
        ),
    ]
