# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_auto_20170717_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='messenger.MessageThread'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('Q', 'QUEUED'), ('P', 'PROCESSING'), ('F', 'FINISHED'), ('E', 'EXPIRED')], default='Q', max_length=1),
        ),
    ]
