# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_auto_20170717_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='messenger.MessageThread'),
        ),
    ]
