# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_auto_20170717_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
