# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_auto_20170717_0713'),
        ('messenger', '0010_merge_20170717_0633'),
    ]

    operations = [
    ]
