# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_merge_20170718_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 6, 5, 46, 769626)),
        ),
    ]
