# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_merge_20170718_0351'),
        ('messenger', '0015_merge_20170718_0459'),
    ]

    operations = [
    ]
