# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_merge_20170718_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
