# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0016_auto_20170719_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
