# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_auto_20170719_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
