# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0016_archive_expiry'),
        ('messenger', '0018_auto_20170719_0626'),
    ]

    operations = [
    ]
