# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0020_auto_20170720_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 3, 33, 56, 929301)),
        ),
    ]
