# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0021_auto_20170725_0309'),
        ('messenger', '0021_auto_20170725_0328'),
    ]

    operations = [
    ]
