# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0021_auto_20170725_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 5, 51, 57, 648425)),
        ),
    ]
