# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0024_auto_20170725_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 8, 26, 21, 531659)),
        ),
    ]
