# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0025_auto_20170725_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='access_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='access_secret',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 8, 27, 23, 551264)),
        ),
    ]
