# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0026_auto_20170725_0822'),
        ('messenger', '0022_merge_20170726_0426'),
    ]

    operations = [
    ]
