# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0027_merge_20170726_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 4, 40, 34, 809735)),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.SiteProfile'),
        ),
    ]
