# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0029_auto_20170727_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 2, 32, 13, 21799, tzinfo=utc)),
        ),
    ]
