# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_profile_ip_address'),
        ('messenger', '0030_auto_20170727_0257'),
    ]

    operations = [
    ]
