# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0031_merge_20170727_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 9, 4, 28, 955593)),
        ),
    ]
