# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0032_auto_20170727_0859'),
        ('messenger', '0032_auto_20170728_0224'),
    ]

    operations = [
    ]
