# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0034_auto_20170728_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 10, 14, 41, 841345, tzinfo=utc)),
        ),
    ]
