# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0035_auto_20170728_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 1, 30, 26, 62146, tzinfo=utc)),
        ),
    ]
