# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_content', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('widget_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='widget_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='widgetmessage',
            name='widget_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_content', to='widget.WidgetThread'),
        ),
    ]
