# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 04:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='WidgetThread',
            new_name='MessageThread',
        ),
        migrations.RemoveField(
            model_name='widgetmessage',
            name='widget_sender',
        ),
        migrations.RemoveField(
            model_name='widgetmessage',
            name='widget_thread',
        ),
        migrations.DeleteModel(
            name='WidgetMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_content', to='widget.MessageThread'),
        ),
    ]
